In [1]:
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

<h2>Задача 1</h2>

In [3]:
a = np.array([
    [1, 2, 1],
    [-2, 1, 1],
])
b = np.array([
    [3, 1],
    [-1, 0],
    [2, 4]
])
c = np.array([
    [-2, 2],
    [1, -1],
    [1, 2],
])

<p>A + 2B</p>

In [5]:
a.T + 2 * b

array([[7, 0],
       [0, 1],
       [5, 9]])

B + 2C

In [6]:
b + 2 * c

array([[-1,  5],
       [ 1, -2],
       [ 4,  8]])

<h2>Задача 2</h2>

In [23]:
matrix = np.zeros((8, 8), dtype=np.uint8)

In [24]:
matrix[::2, 1::2] = 1

In [25]:
matrix[1::2, 0::2] = 1

In [26]:
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=uint8)

<h2>Задача 3</h2>

In [40]:
vector1 = np.linspace(0, 1.4, 15)
vector2 = np.linspace(1, 6, 6)

In [41]:
matrix1 = np.reshape(vector1, (5, 3))
matrix2 = np.reshape(vector2, (3, 2))

In [42]:
result = matrix1 @ matrix2 

In [43]:
matrix1

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8],
       [0.9, 1. , 1.1],
       [1.2, 1.3, 1.4]])

In [44]:
matrix2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [45]:
result

array([[ 1.3,  1.6],
       [ 4. ,  5.2],
       [ 6.7,  8.8],
       [ 9.4, 12.4],
       [12.1, 16. ]])

<h2>Задача 4</h2>

In [47]:
vector = np.array([2 * i + 1 for i in range(36)], dtype=np.int32)

In [51]:
vector

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71])

In [50]:
vector[vector % 3 == 0]

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69])